# Welcome to Jekyll!
#
title: Review of the decade
description: >- # this means to ignore newlines until "baseurl:"
  #
baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000 # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
    sass_dir: _sass
    style: compressed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
